### ISSUE TITLE
Make host and port easier to configure in forks

### ISSUE THREAD

**Issue by k3d3** [Upload/upclient#2]
Currently there are a few places in the source where the host, port and/or API key need to be changed. Instead, this should be in a separate json file, or globally defined at the top of upclient.js.

**Comment by ultramancool** [comment]
Don't really think port needs to be done, just host URL should work, as it is in ShareX already.

**Comment by anarcat** [comment]
i believe this is a dupe of #1.

**Comment by k3d3** [comment]
This is actually not a duplicate - this one is for people forking the Up1 code and running their own service, allowing them to set a default easier.

#1 is for using the main Up1 upclient (or any other one) and using it to upload to any arbitrary server by giving arguments to the command.

**Comment by k3d3** [comment]
Closed by #8.
